version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ./backend.entrypoint.sh
    volumes:
      - ./media:/app/media

  rqworker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "
      echo 'Warte auf PostgreSQL...';
      while ! pg_isready -h $DB_HOST -p $DB_PORT -q; do sleep 1; done;
      echo 'PostgreSQL bereit, starte Worker...';
      python manage.py rqworker default
      "
    volumes:
      - ./media:/app/media

volumes:
  postgres_data:
  redis_data:
